### ISSUE TITLE
Input data changes 

### ISSUE THREAD

**Issue by bitterbark** [NOAA-GFDL/MDTF-diagnostics#126]
As the number of pods grow, so will the size of the single obs_data tar file. This is ineffficient for downloading as well as for me creating the file. I can see we want an easy way for someone to run the whole thing, but are any users really going to do want it all? Would it make more sense to have a directory of individual tar/data files and provide a script to users to select which ones they want to download? Or have some of the changes to the framework dealt with this already?

**Comment by tsjackson-noaa** [comment]
Good point @bitterbark -- this has come up in discussion a few times already, and we should decide what we're going to do about it before the gen 2 PODs get here. Handling the data submission manually isn't scalable and isn't a good use of your time, and we should try to automate this as much as possible.

- I'd be in favor of separating the obs data for individual scripts like you proposed, since this would support users installing the subset of PODs they want, and reduce the amount of data that needs to be downloaded when those PODs are updated. I'd propose an FTP directory structure like `ftp.cgd.ucar.edu/archive/mdtf/MDTF_obs_data/`\<POD name\>`/yyyymmdd.tar`, with "\<POD name\>`_latest.tar`" as a symlink to the most recent tarball. This would be a bonus for provenance as well, since we could include the obs data revision date in the POD output and warn the users if their data isn't current (by including a file in the MDTF code repo with the latest revisions.)

- On the other hand, I don't think it would be a  great user experience if we made them download and extract a dozen-plus separate tarballs before they could use the package. I can think of two ways to address this:
  - Have the package do things instead of the users: the current "one-stop" installer script has [code](https://github.com/NOAA-GFDL/MDTF-diagnostics/blob/e0cb7cd1a202438cd0a3c3986e63afe27ccd85b6/src/install.py#L90-L150) for fetching and extracting tarballs, which could be adapted to this case -- we'd change the installation instructions to make the install script the preferred method of installation, and it would ask the user for desired PODs and download the files for them, as you suggested.
    I'd advocate for this as the best long-term solution, since we can add/change functionality in the script (eg changing hosting site) without having to train users to follow a new set of instructions. I spent a while trying to handle possible connection errors etc. in the install script, so I'm willing to stand behind it (although I'm not claiming it's perfect...). 
  - Automate the tarball creation: "make a new tarball when any of the source files are updated" is a good use case for makefiles, if doing everything with the installer script isn't desirable.

**Comment by bitterbark** [comment]
I like the directory structure you propose, @tsjackson-noaa, and having an automated capability would be good too. I also advocate for a simple solution in case the "do everything for me" script doesn't work: producing a file that can be input to ftp to get the necessary files, along with the command to do it. 

As a side note, in our discussions about new pods needing different data, should we have a list of the existing obs products (and their degree of digestion) for developers to reference? For instance, Rich Neale's diurnal precipitation pod has 3-hrly precip data from GPCP and TRMM; it isn't unlikely that other precipation-related pods might be able to make use of that.
