### ISSUE TITLE
Seeking clarification on variable naming convention 

### ISSUE THREAD

**Issue by jfbooth** [NOAA-GFDL/MDTF-diagnostics#142]
We used the following website to identify the proper variable name:
http://cfconventions.org/Data/cf-standard-names/72/build/cf-standard-name-table.html

However, on that website we could not find all of variables that we use in our POD
- 10m wind speeds - not available on the CF standard name table list. From my previous work with CMIP data, 10m wind speeds have been referred to as U10 and V10. But it not listed on the website.
- upward vertical velocity is WAP. We only need WAP at 500hpa, should we use the generic WAP variable name, or should we be more specific?
- Land/ocean mask - short name of the variable is not available.
- surface height - not clear which variable name to use 

Questions: 
1. Are we using the correct website to confirm standard variable names?
2. Any preference on what we should do for naming the variables listed above?

Thank you,
Jimmy

**Comment by tsjackson-noaa** [comment]
Hi @jfbooth, sorry for taking so long to reply. 

- Cases 1 and 2 can be implemented in the current settings file format, since they both take the form of "requesting a CF variable at a set vertical level"; in other words, they're not defining a new physical quantity. 

  In the POD settings file, this is done with the [scalar coordinates](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.8/cf-conventions.html#scalar-coordinate-variables) attribute on the varlist entry: in the [example](https://mdtf-diagnostics.readthedocs.io/en/latest/sphinx/ref_settings.html#varlist-entry-example) given in the documentation, we request **u** on a 500hPa level by defining a vertical coordinate named ``pressure`` (standard name `air_pressure`) with units of hPa in the [dimensions section](https://mdtf-diagnostics.readthedocs.io/en/latest/sphinx/ref_settings.html#dimensions-section) of the settings file, and specifying that the variable in question should be extracted at the isosurface where that coordinate takes the value `500`. 

  For your first case, this can similarly be done by defining a vertical coordinate with standard name `altitude`, with units in meters.

- For case 3, the CF standard name list defines `land_area_fraction`, `sea_area_fraction`, etc. which are used in the CMIP6 data request. Depending on your use case, `land_binary_mask`, `sea_binary_mask` may be relevant instead.

- For case 4, I believe you'd want `surface_altitude` (`orog`), or more generally `geopotential height` (`zg`) to translate between pressure levels and altitude.

In general, searches on the CF convention [standard name table](http://cfconventions.org/Data/cf-standard-names/77/build/cf-standard-name-table.html) are more productive if you select the "also search help text" box.

There are cases where there is no CF convention standard name for the POD needs. For these cases, the [use_exact_name](https://mdtf-diagnostics.readthedocs.io/en/latest/sphinx/ref_settings.html#varlist-entry-example) flag can be set on the varlist: setting this to `True` disables the variable name translation entirely, and tells the package to only look for a variable with the exact name given in the varlist. As the documentation for this setting describes, this means the data request for your POD will almost certainly fail if a user tries to run your POD on a model with a different naming convention.

**Comment by jfbooth** [comment]
@tsjackson-noaa Thanks for the clarification. This is great. We will adjust accordingly.
