### ISSUE TITLE
Suggestion to review MDTF installation process documentation

### ISSUE THREAD

**Issue by aradhakrishnanGFDL** [NOAA-GFDL/MDTF-diagnostics#151]
The documentation is great for the MDTF and I was able to install it using the git approach. Here are just a few things that I'm bringing to your attention to assess and check what may need to be rephrased/removed so a new user finds an unambiguous way to have MDTF installed in their environment. 

The quick start installations indicate the following ways to install the MDTF package, one being pointed to GitHub and the other geared towards downloading a zip file. They both may apply to different types of users, but clarifying that would be helpful, should the download option still be relevant and accurate. 

-The official repo for the MDTF code is hosted at the NOAA-GFDL GitHub account. We recommend that end users download and test the latest official release.

-To install the MDTF package on a local machine, create a directory named mdtf and unzip the code downloaded_ ....

-The [documentation site](https://mdtf-diagnostics.readthedocs.io/en/latest/
) pointers from the README.md (first paragraph) seems to be focused on the git-way of doing things, which is nice. Section 1.1 and the first paragraph could be more consistent.

**Comment by wrongkindofdoctor** [comment]
@aradhakrishnanGFDL @tsjackson-noaa @jkrasting Yes, we definitely need to clarify how to install the latest stable version of MDTF (target audience is end-users) versus the develop branch (target audience is POD contributors and framework developers). I  think it would be simpler to instruct both audiences to use the git method, since the only difference is the starting branch and use of git checkout tags: 
* end users: 
  - Clone the MDTF repo
  - verify that you are on the main branch (this is the default, but it never hurts to get in the habit of running `git branch` before you start working)
  - run `git checkout tags/[version name]`
  - proceed with the installation process
  - check out a new branch that will contain your edited config files: `git checkout -b [branch name]`
  - update the config files, then push branch+updates to your remote fork: `git push -u origin [branch name]`
  * developers:
    - clone the MDTF repo
    - verify that you are on the develop branch
    - proceed with the installation process
    - checkout a new branch for your POD: `git checkout -b [branch name]`
    - do some work, then push the branch to your remote fork: `git push -u origin [branch name]`
