### ISSUE TITLE
Speed up the Conda environment installation process

### ISSUE THREAD

**Issue by wrongkindofdoctor** [NOAA-GFDL/MDTF-diagnostics#160]
Updating the conda environments reportedly takes anywhere from 10--30 min depending on the system when running `./conda_env_setup --all`. This may not be a huge issue for users who update their MDTF repos infrequently. However, it is the most time-consuming process  in the CI, where every build requires running conda_env_setup, and the conda installation process takes ~12 min on average.

The Anaconda blog has some [suggestions](https://www.anaconda.com/blog/understanding-and-improving-condas-performance) for improving performance, though it looks like we are already using most of them (e.g., the environment files already specify exact versions for most of the packages).

Another solution might be to use [mamba](https://github.com/mamba-org/mamba)--the C++ version of the conda package manager.

**Comment by tsjackson-noaa** [comment]
Good point -- unfortunately this is something we've been struggling with for a long time, and any improvements will be enthusiastically accepted!

- I don't see any downside to mamba: as far as I can tell, it's meant as a drop-in replacement for conda with better performance, so getting the package to use it would be a matter of find-and-replace. We went with conda because the user probably already has conda installed somewhere, while mamba is still ahead of the curve in terms of adoption. 

- For the record, a while back @jkrasting put the dependencies for all PODs in a single conda environment and was able to get it to install (after an even longer wait) -- see PR NOAA-GFDL/MDTF-diagnostics#23. I'm not sure how much of a speedup this would be for CI, and it would also mean that CI is done in a different environment than we deploy in (at the level of sub-minor version numbers), so I'm hesitant to recommend it.

**Comment by jkrasting** [comment]
I am not certain on this, but packing up MDTF via conda-build may do some of the heavy lifting in terms of solving the environment ahead of time.  This could reduce the time spent by the user (or CI) if we had `conda install -c noaa-gfdl mdtf-diagnostics`

**Comment by tsjackson-noaa** [comment]
For future reference: the mamba project also describes [micromamba](https://gist.github.com/wolfv/fe1ea521979973ab1d016d95a589dcde), a minimal, statically-linked version of (conda+mamba) that would take the place of the miniconda install in CI (or for users). It's characterized as being experimental, and doesn't support some of the features of conda that we use (see discussion in the link), so I don't think we should adopt it now, but we should keep an eye on it as it matures.
