### ISSUE TITLE
Framework installation fails with the latest Anaconda/Miniconda with Python 3.9

### ISSUE THREAD

**Issue by yihungkuo** [NOAA-GFDL/MDTF-diagnostics#233]
@jkrasting, @tsjackson-noaa, @wrongkindofdoctor The package as in PR #161 (and I suspect for other recent branches as well) doesn't work with the latest version of Anaconda/Miniconda installers with Python version 3.9 (tested and worked for py3.8 and py3.7). Either the package has to be updated somehow, or the documentation should specify the versions of Anaconda/Miniconda installers.

Also, from experience helping @xiananjiang: The relations among per-existing conda under /usr/ and the one provided by individual users' Anaconda/Miniconda installation, and the _MDTF_* conda environments are confusing. @xiananjiang thought that he was working with his own Miniconda installation, but actually was using the per-existing conda (and the relevant library versions were inconsistent with the one provided by _MDTF_*). He has since fixed the conda installation/environment problem, and started working on the POD again. I would suggest that the conda-command/environment-section in the documentation should be expanded and do a better job in explaining things and giving instructions. This could potentially save the POD developers' time and effort.

**Comment by wrongkindofdoctor** [comment]
@yihungkuo Thanks for helping @xiananjiang with the anaconda installation issues. I agree that adding verified functional versions of anaconda3/miniconda3 to the docs would be helpful.

I did a fresh installation of miniconda3 on my Linux workstation with python 3.9, and did not encounter any issues installing the framework, or running the test cases in default_tests.jsonc using the latest develop branch.

If you could add output from error logs and/or the terminal, and point to the branch(es) you were working on, we can try to figure out why the installation failed on your system.

**Comment by tsjackson-noaa** [comment]
Echoing what @wrongkindofdoctor said, we can't diagnose the problem without more details. Terminal output describing what went wrong would help, and steps to reproduce the problem would be better.

The version of python provided by the conda installer (in the base environment) is never used, either in framework installation or operation. The version of python in the conda environment used by the framework (called by the wrapper shell script) is pinned to 3.7. 

Multiple installations of conda cannot coexist, and trying to install an "individual users' Anaconda/Miniconda installation" over top of a "pre-existing conda installation" will break one or the other. This is clearly described in the [installation instructions](https://mdtf-diagnostics.readthedocs.io/en/latest/sphinx/start_install.html?highlight=conda#installing-the-conda-package-manager), and I don't think we can't state it more directly. This limitation is due to the way conda is implemented, and there's nothing we can do about this as long as we use conda for dependency management. See [this comment](https://github.com/NOAA-GFDL/MDTF-diagnostics/pull/208#pullrequestreview-657123052).

The conda commands used by our installation script have not changed since conda version 4.4, so without further information my guess is that the reported issue was caused by a broken conda installation.

**Comment by yihungkuo** [comment]
@wrongkindofdoctor @tsjackson-noaa Thanks for clarifying. I can confirm that the framework actually works with py39. I did some follow-up tests and found the cause of the problem---bad luck + carelessness on my part! Sorry. Also, if appropriate, I can change the title of this issue to better characterize it.

Here's what happened. Before a meeting with @xiananjiang, I tested PR #161 because there are certain features @xiananjiang may find useful. I did this on a backup laptop and set up the conda environments using the latest Miniconda installer with py39. The framework failed to produce output because of insufficient disk space (and I missed the warning message for this)---I forgot that the current framework copies model data into $WK_DIR. The framework handled the errors well, and deleted the copied model data afterward. In any events, I couldn't figure this out at the time, and incorrectly assumed there might be problems with either the framework code or conda/python version.
A couple of days later, I tested again, on a different laptop with more disk space, using 3 latest versions of Miniconda installers (with py37, py38 and py39) trying to figure out whether python version caused the problem. The tests went well for py37 and py38. When setting up the conda environments with the py39 installer, $CONDA_ENV_DIR was created but empty---my best guess of the cause is intermittent internet connection and/or a possible typo when I input the commend. And because of my confirmation biases from prior test, I incorrectly jump to conclusion that the framework wasn't compatible with py39. 

I apologize for my carelessness, causing the confusion, and that you have to spend time looking into this. Also I would like to suggest adding one line to README.md around section 1.2, warning about the additional disk space required by copying data into $WK_DIR. README.md already includes the disk space requirement for the sample model data and conda environments, but copying data adds a substantial fraction to the required space.

**Comment by wrongkindofdoctor** [comment]
@yihungkuo It sounds like you had quite an...adventure debugging the disk space problem (I run into this  problem frequently when I forget to switch the wkdir to a location outside of my home directory on my workstation). I'll go ahead and add a note for users to make sure that they are writing output to a location with sufficient space for the test data plus additional data for their own PODs.
