### ISSUE TITLE
Update the mdtf_gfdl.csh script

### ISSUE THREAD

**Issue by wrongkindofdoctor** [NOAA-GFDL/MDTF-diagnostics#242]
[mdtf_gfdl.csh](https://github.com/NOAA-GFDL/MDTF-diagnostics/blob/develop/sites/NOAA_GFDL/mdtf_gfdl.csh) needs to be updated to point to new central installations of MDTF-diagnostics and inputdata directories on GFDL systems. The executable src/mdtf_gfdl.py was renamed and relocated (see commit [29d7781](https://github.com/NOAA-GFDL/MDTF-diagnostics/commit/29d77817c0cb2df80aed784ead1b8f1df99a366a#diff-25a6634263c1b1f6fc4697a04e2b9904ea4b042a89af59dc93ec1f5d44848a26)) and needs to be updated to point to the correct module.

**Comment by wrongkindofdoctor** [comment]
@tsjackson-noaa Can you provide more insight into what happened to [mdtf_gfdl.py](https://github.com/NOAA-GFDL/MDTF-diagnostics/blob/426a76c3110a7c947ab1a04efa138958ff4c6cc2/sites/NOAA_GFDL/mdtf_gfdl.py)? It disappears from sites/NOAA-GFDL in commit [a07d8ba](https://github.com/NOAA-GFDL/MDTF-diagnostics/commit/a07d8ba9ede702358708e5584d6bfe083dbf11f1#diff-25a6634263c1b1f6fc4697a04e2b9904ea4b042a89af59dc93ec1f5d44848a26), it is no longer included in sites/NOAA_GFDL, but the commit log doesn't show that it was renamed or deleted.

**Comment by tsjackson-noaa** [comment]
@wrongkindofdoctor -- good catch, and turns out I spoke too soon when I claimed I couldn't think of any changes that broke this script. 

mdtf_gfdl.py was the GFDL-specific entry point to the MDTF package -- it got removed for reasons of avoiding code duplication, and making testing manageable down the line (we want to make any site-specific code as small as possible, and avoid having a bunch of "top-level" scripts that we all need to test). Its functionality was replaced by the "--site=NOAA_GFDL" command-line argument.

I'm working on a PR that will fix these changes (just wasted a bunch of time trying to pass through unrecognized arguments with getopt in tcsh).
