### ISSUE TITLE
How to provide 10m wind speeds to the POD? 

### ISSUE THREAD

**Issue by jeyavinoth** [NOAA-GFDL/MDTF-diagnostics#262]
@jfbooth @jkrasting @tsjackson-noaa @wrongkindofdoctor 

Our POD requires 10m wind speeds and omega @ 500hPa. I was able to get omega working at 500hPa using the "scalar_coordinates" attribute in the "varlist" section of "settings.jsonc."

How do I go about doing something similar for the u10 and v10 (eastward_wind and westward_wind at 10m)? It seems like the altitude coordinate is not available for the "ua" / "va" variables. It would be great if you can provide me with an example. 

Thanks, 
JJ

**Comment by wrongkindofdoctor** [comment]
@jkrasting @tsjackson-noaa I think this will require new entries to the CMIP fieldlist table since u10 and v10 are not defined on pressure levels. If it is not possible with the current 4-D data processing code, we need consider how we will support other vertical coordinates. such as atmospheric height,  land data soil depths, ocean depth and potential temperature levels.

**Comment by jfbooth** [comment]
Thanks for the comment @wrongkindofdoctor
@jkrasting @tsjackson-noaa @jeyavinoth 

First: we agree: we cannot find surface winds as a variable from the standard list. [CF Standard table](http://cfconventions.org/Data/cf-standard-names/72/build/cf-standard-name-table.html). This surprised us because we have worked with CMIP model output which provide surface wind speeds as "uas" and "vas" ("zonal wind component at 10 m"; "meridional wind component at 10 m"). We were under the impression that these are standard output data from GCMs. 

Would it be possible to simply add "uas" and "vas" to the CF fieldlist table? (We agree with Jess that the team might want to consider how you will support other vertical coordinates. But that sounds like a big task, and for our purposes it might not be necessary.)

If a small quick change like the one I suggested is not possible, JJ and I are just going to replace the surface winds metric in our POD with a metic using winds on the 850-hPa level instead of the surface winds. 

Thanks,
Jimmy

**Comment by jkrasting** [comment]
It is my understanding too that `uas` and `vas` are standard variables.  Here are the entries in the CMIP6 data request:

- [uas](http://clipc-services.ceda.ac.uk/dreq/u/e72b243a2a1c8691ab0168d8b62534c2.html)
- [vas](http://clipc-services.ceda.ac.uk/dreq/u/86b1cd51f370e346ecb20f1e80cb6ea4.html)

**Comment by aradhakrishnanGFDL** [comment]
@wrongkindofdoctor Based on the CMOR specifications, as John mentions-- the uas vas may be what we are looking for here.

https://github.com/PCMDI/cmip6-cmor-tables/blob/master/Tables/CMIP6_Amon.json#L1286   (At 10m "dimensions": "longitude latitude time height10m")

**Comment by jeyavinoth** [comment]
Do you have any updates on this issue? 

Thanks, 
JJ

**Comment by wrongkindofdoctor** [comment]
@jeyavinoth I'm working with @tsjackson-noaa to get this implemented. I'm new to OO programming, so it's a steep learning curve, but we've got some preliminary work completed, and are debugging.

**Comment by wrongkindofdoctor** [comment]
@jeyavinoth 10-m wind speed (and other atmospheric surface variables defined at a height) are now specified with the  `atmos_height` 'modifier' attribute in a POD's settings.jsonc file. See the example [settings.jsonc](https://github.com/NOAA-GFDL/MDTF-diagnostics/blob/9f9db8d5419d12a4e97d540c6b517a2620be8fc5/diagnostics/example/settings.jsonc#L76-L82) for reference.
