### ISSUE TITLE
Implement LGTM code scanning

### ISSUE THREAD

**Issue by jkrasting** [NOAA-GFDL/MDTF-diagnostics#54]
The GitHub LGTM integration will be turned on for this repository to meet internal security requirements.

**Comment by tsjackson-noaa** [comment]
@jkrasting , does LGTM only run on pull requests? I made some commits last night to fix issues in the framework code that LGTM turned up, but the badges and [dashboard](https://lgtm.com/projects/g/NOAA-GFDL/MDTF-diagnostics/?mode=list) haven't updated (still reflecting commit cd105e8; main is currently on ec06916be9208feeca170f4beb1d44e4c7b01a53).

Overall, I was impressed -- I've been using pylint while I've been writing the framework code, and LGTM caught legitimate potential errors that that missed, as well as being able to trace code flow across scopes (eg warnings that a variable definition is never used, because its value always gets overwritten somewhere else.)

**Comment by jkrasting** [comment]
@tsjackson-noaa, it does seem rather comprehensive. 

I'm not sure if it is only running on PRs - It says it is currently "Running analyses for revisions" in the [History ](https://lgtm.com/projects/g/NOAA-GFDL/MDTF-diagnostics/history/) section.  Maybe this includes ec06916?

**Comment by tsjackson-noaa** [comment]
@jkrasting : looks like the update eventually happened: I didn't notice how long ago, but the tracker now reflects the issues I fixed. I don't have any other comments or action items -- if LGTM is set up to your satisfaction, feel free to close this issue.

**Comment by jkrasting** [comment]
I believe it is running continuously so eventually the updates should be detected.  Glad it worked.  Thanks @tsjackson-noaa.
